# Generated by Django 6.1.1 on 2026-09-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('roll_number', models.IntegerField()),
            ],
        ),
    ]
